# -*- coding: utf-8 -*-
"""HR_Employee_data_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vl0q6Hg4RFwb0A55nOJfRjZSedvgBVwu

# Cleaning
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/HR Employee data.csv")
df

df.info()

df.dtypes

single_value_columns = df.columns[df.nunique() == 1]
single_value_columns

df.drop(columns=["EmployeeCount" , "Over18" , "StandardHours"],inplace=True)

df.columns

current_year = 2025
df["Tenure"] = df.apply(lambda row: current_year - row["JoiningYear"] if pd.isna(row["LeavingYear"]) else row["LeavingYear"] - row["JoiningYear"], axis=1)

df["LeavingYear"] = df["LeavingYear"].fillna("Still Employed")

df["Reason"] = df["Reason"].fillna("Still Active")

df["RelievingStatus"] = df["RelievingStatus"].fillna("Employment Ongoing")

df["EmploymentStatus"] = df["LeavingYear"].apply(lambda x: "Still Employed" if x == "Still Employed" else "Left")

df.duplicated().sum()

df.isnull().sum()

df.describe()

df.dtypes

"""#Business Questions

1. What is the average monthly income by job level?
 Insight: Helps identify if higher job levels are indeed associated with higher salaries.
"""

df.groupby('JobLevel_updated')['MonthlyIncome'].mean()

"""2. What are the most common reasons employees leave the company?
Insight: Reveals key drivers of attrition based on employee feedback.
"""

df['Reason'].value_counts(normalize=True) * 100

"""3. What is the average tenure at the company for employees who leave vs. those who stay?
Insight: Measures employee retention based on length of service.
"""

df.groupby('Attrition')['YearsAtCompany'].mean()

"""4. What is the average performance rating by office location?
Insight: Detects geographical differences in employee performance.
"""

df.groupby('office_code')['PerformanceRating'].mean()

"""5. How many employees live more than 10 km from the office?
Insight: Identifies employees who may experience long commutes and potential burnout.
"""

df[df['DistanceFromHome'] > 10].shape[0]

"""6. Does working overtime impact job satisfaction?
Insight: Measures the effect of overtime on employee happiness.
"""

df.groupby('OverTime')['JobSatisfaction'].mean()

"""7. What percentage of married employees work in each department?
Insight: Highlights how departments differ in demographic composition.
"""

df[df['MaritalStatus'] == 'Married']['Department'].value_counts(normalize=True) * 100

""" 8. What is the average number of companies worked at, by education field?
Insight: Checks if educational background relates to job stability.
"""

df.groupby('EducationField')['NumCompaniesWorked'].mean()

"""9. Is there a correlation between working overtime and employee attrition?
Insight: Assesses whether long working hours contribute to resignations.
"""

pd.crosstab(df['OverTime'], df['Attrition'], normalize='index') * 100

"""11. What is the average tenure by employment status?
Insight: Understands if full-time vs. contract workers differ in loyalty.

12. Does environmental satisfaction affect performance rating?
Insight: Evaluates the link between workplace environment and productivity.
"""

df.groupby('EnvironmentSatisfaction')['PerformanceRating'].mean()

df.groupby('EmploymentStatus')['Tenure'].mean()

"""# Visuals

10. Which age group has the highest attrition rate?
Insight: Identifies age-related turnover trends.
"""

df[df['Attrition'] == 'Yes']['Age'].plot.hist(bins=10)

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="Attrition", y="Tenure", palette="Set2")
plt.title("Tenure Distribution by Employee Attrition", fontsize=14, fontweight='bold')
plt.xlabel("Attrition", fontsize=12)
plt.ylabel("Tenure (Years)", fontsize=12)
plt.xticks(fontsize=11)
plt.yticks(fontsize=11)
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,5))
sns.barplot(data=df, x="Attrition", y="JobSatisfaction", palette="Set2", estimator=np.mean)
plt.title("Average Job Satisfaction by Attrition", fontsize=14, fontweight='bold')
plt.ylabel("Average Job Satisfaction (1 to 4)")
plt.xlabel("Attrition")
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))

sns.regplot(
    data=df,
    x="Age",
    y="MonthlyIncome",
    scatter_kws={"alpha": 0.4, "color": "steelblue"},
    line_kws={"color": "red", "lw": 2}
)

plt.title("Relationship Between Age and Monthly Income", fontsize=14, fontweight='bold')
plt.xlabel("Age", fontsize=12)
plt.ylabel("Monthly Income", fontsize=12)
plt.xticks(fontsize=11)
plt.yticks(fontsize=11)
plt.grid(True, linestyle="--", alpha=0.3)
plt.tight_layout()
plt.show()

numeric_cols = ['Age', 'MonthlyIncome', 'DistanceFromHome', 'TotalWorkingYears', 'PerformanceRating', 'Tenure',
                'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

plt.figure(figsize=(12, 8))
corr = df[numeric_cols].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numeric Features', fontsize=16, fontweight='bold')
plt.show()

plt.figure(figsize=(10,6))
sns.boxplot(data=df, x='OverTime', y='MonthlyIncome', hue='PerformanceRating', palette='Set2')
plt.title('Monthly Income by OverTime and Performance Rating')
plt.xlabel('OverTime')
plt.ylabel('Monthly Income')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Age', y='YearsAtCompany', hue='PerformanceRating', palette='viridis', alpha=0.7)
plt.title('Age vs Years At Company colored by Performance Rating')
plt.show()

plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='BusinessTravel', hue='PerformanceRating', palette='Set1')
plt.title('Performance Rating Distribution across Business Travel Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='Attrition', hue='OverTime', palette='Set1')
plt.title('Attrition Count by OverTime')
plt.show()

attrition_counts = df['Attrition'].value_counts()

plt.figure(figsize=(6,6))
plt.pie(attrition_counts, labels=attrition_counts.index, autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Set1'))
plt.title('Employee Attrition Distribution')
plt.axis('equal')
plt.show()

income_by_year = df.groupby('JoiningYear')['MonthlyIncome'].mean().reset_index()

plt.figure(figsize=(10,6))
sns.lineplot(data=income_by_year, x='JoiningYear', y='MonthlyIncome', marker='o', color='red')
plt.title('Average Monthly Income by Joining Year')
plt.xlabel('Joining Year')
plt.ylabel('Average Monthly Income')
plt.grid(True)
plt.show()

df.to_csv("HR_Employee_data_cleaned.csv", index=False)